### ISSUE TITLE
Add a color fill for the legend

### ISSUE THREAD

**Issue by googlogmob** [microsoft/powerbi-visuals-gantt#3]
Please add the ability to choose the colors for the each element of legend **individually**
Like this in line diagram http://prntscr.com/dv88eh

**Comment by ignatvilesov** [comment]
Hello @googlogmob ,

Thanks for your feedback.
We'll consider this ability in future versions of the visual.

**Ignat Vilesov,**
Software Engineer

**Microsoft Power BI Custom Visuals**
pbicvsupport@microsoft.com

**Comment by jmcintire** [comment]
Is this planned for a near future release?  I need this for a project to highlight task status by color.  For example, overdue = red, complete = green, in progress = blue, etc.  If not, can anyone point me to source code of another component that allows report developers to hand pick the element color?  I'm happy to take a whack at this myself.

**Comment by zBritva** [comment]
@jmcintire You can calculate the status by add a new column in the PowerQuery editor:

```
if [IsComplete] then "Completed" 
else 
if [Spent time] <= [Estimated time] then "In progress"
else
if [Spent time] > [Estimated time] then "Overdue"
else "Undefined"
```

![image](https://user-images.githubusercontent.com/10897951/63838115-6bec6a80-c985-11e9-8d2c-51f76d56b3c7.png)

**To use legends you should fill Duration filed instead End date**

The limitation will be fixed in the next version.
