### ISSUE TITLE
Data Labels > Position - not saving after switch panels 

### ISSUE THREAD

**Issue by albertofilho82** [microsoft/powerbi-visuals-gantt#99]
Configuration on Data Labels > Position - not saving after switch panels or close and open report.
It always brings position TOP as default.

![print](https://user-images.githubusercontent.com/37080912/36988774-6fb56e34-207e-11e8-8372-c69bf7f0debe.png)

**Comment by uve** [comment]
@albertofilho82, I can't reproduce the issue.
Could you please record a screencast video to demonstrate this bug and paste it here?

**Comment by kabtoffe** [comment]
I stumbled upon this too. In my case I use Group Tasks which makes the Position change to Top. Then I switch the setting to Right and all looks well until I switch to another report page and come back. I did some more testing at it seems like this only happens when Group Tasks is enabled. When it's off the setting is retained.

**Comment by helen508light** [comment]
Hi, @albertofilho82 and @kabtoffe !
Thanks for your feedback. 
I managed to reproduce this bug, will add it to backlog

**Comment by helen508light** [comment]
fixed in last versions
